"""Initial migration

Revision ID: 29d1f859ee4a
Revises: 
Create Date: 2025-11-30 16:21:50.205596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d1f859ee4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('pedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_pedidos')
    op.drop_table('pedidos')
    op.drop_table('users')
    # ### end Alembic commands ###
